#ifndef __REFERENCEFORCEUPDATOR_SERVICE_IDL__
#define __REFERENCEFORCEUPDATOR_SERVICE_IDL__

module OpenHRP
{
  interface ReferenceForceUpdaterService
  {
    void echo(in string msg);
  };
};

#endif
